development:
  adapter: postgresql
  encoding: unicode
  database: samso_development
  pool: 5
  username: maxgronlund
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: samso_test
  pool: 5
  username: maxgronlund
  password:
